// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://macnajgqowsxlwerwtpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hY25hamdxb3dzeGx3ZXJ3dHBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzQxOTksImV4cCI6MjA3MzI1MDE5OX0.RcrBeyKURR6hXJc56h_VsTsAtSUCfFHoJXY3wtKs_Vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});